# Public repo: no secrets or personal identifiers here. Secrets come from
# Proton Pass via `pp-sync`. Installers that append to this file belong in
# ~/.zshrc.local instead.

# --- oh-my-zsh ---------------------------------------------------------------
if [ -d "$HOME/.oh-my-zsh" ]; then
  export ZSH="$HOME/.oh-my-zsh"
  ZSH_THEME=""
  plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
  source "$ZSH/oh-my-zsh.sh"
fi

# --- History -----------------------------------------------------------------
export HISTFILE=~/.histfile
export HISTSIZE=1000
export SAVEHIST=1000

# --- Shell -------------------------------------------------------------------
export EDITOR="emacs -nw"

# --- Completion (AWS) --------------------------------------------------------
export PATH=/usr/local/bin:$PATH
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit
[ -x /usr/local/bin/aws_completer ] && complete -C /usr/local/bin/aws_completer aws

# --- Emacs -------------------------------------------------------------------
export PATH="$HOME/.config/emacs/bin:$PATH"
export DOOMDIR="$HOME/.config/doom"

# Emacs Writing Studio profile
ews() { open -na Emacs --args --init-directory "$HOME/.config/ews" "$@"; }
ews-nw() { emacs -nw --init-directory "$HOME/.config/ews" "$@"; }

# --- Languages & tools -------------------------------------------------------
alias python='python3'
alias pip='python3 -m pip'
alias venv='python3 -m venv .venv'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

export PATH="$PATH:$HOME/go/bin"

export BUN_INSTALL="$HOME/.bun"
[ -d "$BUN_INSTALL/bin" ] && export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "$BUN_INSTALL/_bun" ] && source "$BUN_INSTALL/_bun"

[ -d /opt/homebrew/opt/grep/libexec/gnubin ] && export PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"

if [ -d /opt/homebrew/share/guile ]; then
  export GUILE_LOAD_PATH="/opt/homebrew/share/guile/site/3.0"
  export GUILE_LOAD_COMPILED_PATH="/opt/homebrew/lib/guile/3.0/site-ccache"
  export GUILE_SYSTEM_EXTENSIONS_PATH="/opt/homebrew/lib/guile/3.0/extensions"
fi

for _d in "$HOME/.antigravity/antigravity/bin" \
          "$HOME/.antigravity-ide/antigravity-ide/bin"; do
  [ -d "$_d" ] && export PATH="$_d:$PATH"
done
for _d in "$HOME/.lmstudio/bin" \
          "$HOME/Library/Python/3.11/bin" \
          "$HOME/.local/bin"; do
  [ -d "$_d" ] && export PATH="$PATH:$_d"
done
unset _d

# Fix Python SSL certificate errors
[ -x /usr/local/bin/python3 ] && export SSL_CERT_FILE="$(/usr/local/bin/python3 -m certifi 2>/dev/null)"

alias k="kubectl"

# --- Proton Pass -------------------------------------------------------------
# SSH keys are served by the Proton Pass SSH agent (`pass-cli ssh-agent`).
[ -S "$HOME/.ssh/proton-pass-ssh-agent.sock" ] && \
  export SSH_AUTH_SOCK="$HOME/.ssh/proton-pass-ssh-agent.sock"

# Secrets. ~/.config/zsh/secrets.env lists `pass://Vault/Item/field`
# references; `pp-sync` fetches them into ~/.zshrc.local (mode 600), which
# every shell sources. Re-run it after changing a secret.
#
#   pp-sync            refresh the secrets block in ~/.zshrc.local
#   pp <Item> [field]  print one field (default: password)
#   ppc <Item> [field] copy one field to the clipboard, cleared after 45s
PP_SECRETS_FILE="$HOME/.config/zsh/secrets.env"
PP_LOCAL_FILE="$HOME/.zshrc.local"
PP_VAULT="Personal"

pp-sync() {
  # secrets.env is dotenv (KEY=pass://...); `inject` wants {{ pass://... }},
  # so rewrite it into a temp template (references only, no values).
  local tpl out line block tmp rc
  tpl="$(mktemp)" || return 1
  sed -E 's#^([A-Za-z_][A-Za-z0-9_]*)=(pass://.*)$#\1={{ \2 }}#' "$PP_SECRETS_FILE" > "$tpl"
  out="$(pass-cli inject --in-file "$tpl" --force)"; rc=$?
  rm -f "$tpl"
  (( rc == 0 )) || { echo "pp-sync: pass-cli failed; ~/.zshrc.local unchanged" >&2; return $rc; }

  block="# >>> proton-pass secrets: generated by pp-sync, do not edit >>>"$'\n'
  while IFS= read -r line; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    block+="export ${line%%=*}=${(q)${line#*=}}"$'\n'
  done <<< "$out"
  block+="# <<< proton-pass secrets <<<"

  # Replace any previous block atomically, keeping the rest of the file.
  tmp="$(umask 077; mktemp "$PP_LOCAL_FILE.XXXXXX")" || return 1
  { [ -f "$PP_LOCAL_FILE" ] && sed '/^# >>> proton-pass secrets/,/^# <<< proton-pass secrets <<</d' "$PP_LOCAL_FILE"
    print -r -- "$block"; } > "$tmp" && mv "$tmp" "$PP_LOCAL_FILE" && chmod 600 "$PP_LOCAL_FILE"
  eval "$block"
  echo "pp-sync: wrote $(pp--names | wc -l | tr -d ' ') secret(s) to ~/.zshrc.local"
}

pp--names() {
  sed -nE 's/^([A-Za-z_][A-Za-z0-9_]*)=.*/\1/p' "$PP_SECRETS_FILE"
}

pp() {
  [ -n "$1" ] || { echo "usage: pp <item title> [field]" >&2; return 2; }
  pass-cli item view "pass://$PP_VAULT/$1/${2:-password}"
}

ppc() {
  local v
  v="$(pp "$@")" || return 1
  printf '%s' "${v%$'\n'}" | pbcopy
  echo "Copied; clipboard clears in 45s"
  ( sleep 45; [ "$(pbpaste)" = "${v%$'\n'}" ] && printf '' | pbcopy ) &!
}

# --- Secrets and installer blocks (untracked) ---------------------------------
[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"

# --- Prompt (keep last) ------------------------------------------------------
eval "$(starship init zsh)"
