# Public repo: no secrets or personal identifiers here. Secrets come from
# the macOS Keychain via `ks-sync`. Installers that append to this file
# belong in ~/.zshrc.local instead.

# --- oh-my-zsh ---------------------------------------------------------------
if [ -d "$HOME/.oh-my-zsh" ]; then
  export ZSH="$HOME/.oh-my-zsh"
  ZSH_THEME=""
  plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
  source "$ZSH/oh-my-zsh.sh"
fi

# --- History -----------------------------------------------------------------
export HISTFILE=~/.histfile
export HISTSIZE=1000
export SAVEHIST=1000

# --- Shell -------------------------------------------------------------------
export EDITOR="emacs -nw"

# --- Completion (AWS) --------------------------------------------------------
export PATH=/usr/local/bin:$PATH
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit
[ -x /usr/local/bin/aws_completer ] && complete -C /usr/local/bin/aws_completer aws

# --- Emacs -------------------------------------------------------------------
export PATH="$HOME/.config/emacs/bin:$PATH"
export DOOMDIR="$HOME/.config/doom"

# Emacs Writing Studio: a second, vanilla-keybinding profile
ews() { open -na Emacs --args --init-directory "$HOME/.config/ews" "$@"; }
ews-nw() { emacs -nw --init-directory "$HOME/.config/ews" "$@"; }

# --- Languages & tools -------------------------------------------------------
alias python='python3'
alias pip='python3 -m pip'
alias venv='python3 -m venv .venv'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

export PATH="$PATH:$HOME/go/bin"

export BUN_INSTALL="$HOME/.bun"
[ -d "$BUN_INSTALL/bin" ] && export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "$BUN_INSTALL/_bun" ] && source "$BUN_INSTALL/_bun"

[ -d /opt/homebrew/opt/grep/libexec/gnubin ] && export PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"

if [ -d /opt/homebrew/share/guile ]; then
  export GUILE_LOAD_PATH="/opt/homebrew/share/guile/site/3.0"
  export GUILE_LOAD_COMPILED_PATH="/opt/homebrew/lib/guile/3.0/site-ccache"
  export GUILE_SYSTEM_EXTENSIONS_PATH="/opt/homebrew/lib/guile/3.0/extensions"
fi

for _d in "$HOME/.antigravity/antigravity/bin" \
          "$HOME/.antigravity-ide/antigravity-ide/bin"; do
  [ -d "$_d" ] && export PATH="$_d:$PATH"
done
for _d in "$HOME/.lmstudio/bin" \
          "$HOME/Library/Python/3.11/bin" \
          "$HOME/.local/bin"; do
  [ -d "$_d" ] && export PATH="$PATH:$_d"
done
unset _d

# Fix Python SSL certificate errors
[ -x /usr/local/bin/python3 ] && export SSL_CERT_FILE="$(/usr/local/bin/python3 -m certifi 2>/dev/null)"

alias k="kubectl"

# --- Secrets (macOS Keychain) -------------------------------------------------
# SSH keys live in ~/.ssh; macOS's ssh-agent loads them (UseKeychain in
# ~/.ssh/config).
#
# ~/.config/zsh/secrets.env lists variable names. Each one's value is a
# generic password in the login Keychain whose service is the variable name.
# `ks-sync` copies them into ~/.zshrc.local (mode 600), which every shell
# sources. Re-run it after changing a secret.
#
#   ks-add VAR         store a secret (prompts for the value)
#   ks-sync            refresh the secrets block in ~/.zshrc.local
#   ks <service>       print one Keychain generic password
#   ksc <service>      copy it to the clipboard, cleared after 45s
KS_SECRETS_FILE="$HOME/.config/zsh/secrets.env"
KS_LOCAL_FILE="$HOME/.zshrc.local"

ks() {
  [ -n "$1" ] || { echo "usage: ks <service>" >&2; return 2; }
  security find-generic-password -a "$USER" -s "$1" -w
}

ks-add() {
  [ -n "$1" ] || { echo "usage: ks-add <VAR>" >&2; return 2; }
  local v
  read -rs "v?Value for $1: "; echo
  security add-generic-password -U -a "$USER" -s "$1" -l "dotfiles: $1" -w "$v"
}

ks-sync() {
  local name val block tmp
  block="# >>> keychain secrets: generated by ks-sync, do not edit >>>"$'\n'
  for name in $(ks--names); do
    val="$(ks "$name")" || { echo "ks-sync: $name not in Keychain; ~/.zshrc.local unchanged" >&2; return 1; }
    block+="export $name=${(q)val}"$'\n'
  done
  block+="# <<< keychain secrets <<<"

  # Replace any previous block atomically, keeping the rest of the file.
  tmp="$(umask 077; mktemp "$KS_LOCAL_FILE.XXXXXX")" || return 1
  { [ -f "$KS_LOCAL_FILE" ] && sed '/^# >>> keychain secrets/,/^# <<< keychain secrets <<</d' "$KS_LOCAL_FILE"
    print -r -- "$block"; } > "$tmp" && mv "$tmp" "$KS_LOCAL_FILE" && chmod 600 "$KS_LOCAL_FILE"
  eval "$block"
  echo "ks-sync: wrote $(ks--names | wc -l | tr -d ' ') secret(s) to ~/.zshrc.local"
}

ks--names() {
  sed -nE 's/^([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*$/\1/p' "$KS_SECRETS_FILE"
}

ksc() {
  local v
  v="$(ks "$@")" || return 1
  printf '%s' "$v" | pbcopy
  echo "Copied; clipboard clears in 45s"
  ( sleep 45; [ "$(pbpaste)" = "$v" ] && printf '' | pbcopy ) &!
}

# --- Secrets and installer blocks (untracked) ---------------------------------
[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"

# --- Prompt (keep last) ------------------------------------------------------
eval "$(starship init zsh)"
