* Headers
#+begin_src elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

* Low Level
** Custom message handler
This message handler will add the ~@@@~ prefix to any messages I provide.
#+begin_src elisp
(defun my-message (format-string &rest args)
  "Display a personal message prefixed with @@@ in *Messages* buffer."
  (apply #'message (concat "@@@ " format-string) args))
#+end_src

* Custom Functions
** Add folder to load path
#+begin_src elisp
(defun my/add-to-load-path (path)
  "Add PATH to `load-path` and log it using `my-message`."
  (add-to-list 'load-path path)
  (my-message "Added %s to load-path" path))
#+end_src

** Host machine location
This function sets a variable that can be used for a conditional on home/work seperation.
#+begin_src elisp
(setq my-location
      (cond
       ((member system-name '("S427544")) "work")
       ((member system-name '("MacBook-Pro.local")) "home")
       (t "unknown")))
(my-message "Current location: %s" my-location)
#+end_src

** Tangle all files in a specified directory
#+begin_src elisp
(defun my/tangle-org-files-in-directory (directory)
  "Tangle all .org files in the specified DIRECTORY."
  (interactive "DDirectory: ")
  (let ((org-files (directory-files-recursively directory "\\.org\\'")))
    (dolist (file org-files)
      (my-message "Tangling %s..." file)
      (org-babel-tangle-file file))))
#+end_src

** Org Babel Tangle Specific Config Files
#+begin_src elisp
(defun my/org-babel-tangle-on-save ()
  "Auto-tangle specific Org files on save."
  (when (and (string= (file-name-extension buffer-file-name) "org")
             (member (file-name-nondirectory buffer-file-name)
                     my/org-babel-tangle-files))
    (org-babel-tangle)))

(add-hook 'after-save-hook 'my/org-babel-tangle-on-save)
#+end_src

** Check formatter being used
#+begin_src elisp
(defun my/check-formatter-for-mode (mode)
  "Check the formatter used for a specific MODE."
  (interactive
   (list (intern (completing-read "Mode: " obarray
                                  (lambda (m)
                                    (and (fboundp m)
                                         (string-suffix-p "-mode" (symbol-name m))))
                                  t))))
  (with-temp-buffer
    (funcall mode)
    (message "Formatter for %s: %s" mode +format-with)))
#+end_src

* My Variables
** Auto org babel tangle files
List of Org files that should be auto-tangled on save.
#+begin_src elisp
(setq my/org-babel-tangle-files '("zshrc.org" "my-home.org" "my-work.org"))
#+end_src

** Identity
#+begin_src elisp
(setq user-full-name "Paul Meier")
#+end_src

* Shared Modules
#+begin_src elisp
(my/add-to-load-path "~/.config/doom/modules")
#+end_src

* Conditional Machine Loading
This is for private code or anything that shouldn't be included in a public repo.
#+begin_src elisp
(let ((config-dir (format "~/.config/%s" my-location))
      (config-lib (format "my-%s" my-location)))
  (add-to-list 'load-path config-dir)
  (my-message "Added %s to load-path" config-dir)
  (if (locate-library config-lib)
      (require (intern config-lib))
    (my-message "Warning: %s.el not found." config-lib)))
#+end_src

* Beautify Logo
#+begin_src elisp
(setq fancy-splash-image (concat doom-private-dir "alfie.png"))
#+end_src

* Editor
** Drag Lines
#+begin_src elisp
(use-package! drag-stuff
   :defer t
   :init
  (map! "<M-up>" #'drag-stuff-up
        "<M-down>" #'drag-stuff-down
        "<M-left>" #'drag-stuff-left
        "<M-right>" #'drag-stuff-right))
#+end_src

** Emergency log messages only
#+begin_src elisp
(setq warning-minimum-level :emergency)
;;(setq compilation-scroll-output t)
#+end_src

** Full Screen
#+begin_src elisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

** Fonts
#+begin_src elisp
;; "SN Pro" "Roboto Mono" "Fira Code" "Noto Sans Symbols 2"
(setq doom-font (font-spec :family "Fira Code" :size 15)
      doom-variable-pitch-font (font-spec :family "SN Pro" :size 15 :weight 'medium)
      doom-big-font (font-spec :family "Fira Code" :size 24))
#+end_src

** Modeline
#+begin_src elisp
(display-battery-mode 1)
#+end_src

* Projectile
#+begin_src elisp
(setq projectile-project-search-path '("~/Projects"))
#+end_src

* Dired
** Configure Default Directory
If non-nil, Dired tries to guess a default target directory.
#+begin_src elisp
(setq dired-dwim-target t)
#+end_src

* Encryption
#+begin_src elisp
(after! epg
  (setq epg-gpg-program "/usr/local/bin/gpg"
        epg-pinentry-mode 'ask))

(setq epa-file-encrypt-to '("30C3D13A0FBCC050")
      epa-file-select-keys 'silent)

(epa-file-enable)
#+end_src

* Org
** Org View Mode
To hide org markup when viewing a document.
#+begin_src elisp
;;(use-package! org-view-mode)
#+end_src
*** Map view
Don't need this with dooms new +pretty setup
#+begin_src elisp :tangle no
(use-package! evil-org
  :hook (org-mode . evil-org-mode)
  :config
  (map!
   :map evil-org-mode-map
   :localleader
   :desc "View Toggle" "v" #'org-view-mode))
#+end_src

** Org Setup
Needs some cleanup :(
#+begin_src elisp
(defun my/org-mode-setup ()
  (org-indent-mode)
  (variable-pitch-mode 1)
  (auto-fill-mode 0)
  (valign-mode 1)
  (visual-line-mode 1)
  (visual-fill-column-mode 1)
  (display-line-numbers-mode 0)
  (org-display-inline-images)
  (setq evil-auto-indent nil)
  (setq org-attach-id-dir ".attach")
  (setq org-attach-use-inheritance t)
  (setq org-attach-store-link-p t)
  (setq org-attach-dir-relative t)
  (setq org-image-actual-width nil)
  (setq visual-fill-column-center-text t)
  (setq org-log-into-drawer "LOGBOOK")
  (setq org-use-property-inheritance t))

(use-package! org
  :hook (org-mode . my/org-mode-setup)
  :config (define-key org-mode-map (kbd "C-c C-r") verb-command-map))
#+end_src

** Org Babel Config
#+begin_src elisp :tangle no
(setq org-babel-load-languages
      '((emacs-lisp . t)
        (python . t)
        (shell . t)
        (js . t)
        (mermaid . t)
        (scheme . t)
        (verb . t)
        (ein . t)
        (typescript . t)))
#+end_src

** Org Create TODOs from block of lines
#+begin_src elisp
(defun org-set-line-checkbox (arg)
  (interactive "P")
  (let ((n (or arg 1)))
    (when (region-active-p)
      (setq n (count-lines (region-beginning)
                           (region-end)))
      (goto-char (region-beginning)))
    (dotimes (i n)
      (beginning-of-line)
      (insert "- [ ] ")
      (forward-line))
    (beginning-of-line)))
#+end_src

* Verb
#+begin_src elisp
(map! :leader
      (:prefix ("v" . "verb")
       :desc "send request"
       "r" #'verb-send-request-on-point-other-window))
(setq verb-suppress-load-unsecure-prelude-warning t)
#+end_src

* Denote
Always load Denote, I use notes everywhere
** Use Package
#+begin_src elisp
(use-package! denote
  :init
  ;; (require 'denote-journal-extras)
  (add-hook 'denote-after-new-note-hook #'project-and-active-to-agenda)
  (add-hook 'denote-journal-extras-hook 'my-denote-tmr)
  :custom
  (denote-known-keywords '("journal" "active" "project"))
  (denote-prompts '(subdirectory title keywords templates)))
#+end_src

** Customize Denote
#+begin_src elisp
(unless (boundp 'denote-templates)
    (setq denote-templates '()))
;; (setq denote-file-type "markdown-yaml")
(push '(journal . "\n\n* Daily Journal\n\n") denote-templates)
#+end_src

** Keybindings
#+begin_src elisp
(map! :leader
      (:prefix ("e" . "denote")
       :desc "New Note" "n" #'denote
       :desc "Insert Link" "i" #'denote-insert-link
       :desc "New Journal" "j" #'denote-journal-extras-new-or-existing-entry
       :desc "Find in Notes" "f" #'consult-notes-search-in-all-notes
       :desc "Search Notes" "s" #'consult-notes))
#+end_src

** Consult Notes
Consult note dir sources is set in the machine specific profile.
#+begin_src elisp
(use-package! consult-notes
  :config
  (when (locate-library "denote")
    (consult-notes-denote-mode)))
  ;; search only for text files in denote dir
  ;; (setq consult-notes-denote-files-function (function denote-directory-text-only-files)))
#+end_src

* Copilot
** Copilot Keybindings
#+begin_src elisp
(map! :leader
      (:prefix ("l" . "co-chat")
       :desc "Chat Prompt" "p" #'copilot-chat-prompt
       :desc "Reset" "r" #'copilot-chat-reset
       :desc "Chat buffers" "d" #'copilot-chat-display
       :desc "Explain selected" "e" #'copilot-chat-explain
       :desc "Review selected" "v" #'copilot-chat-review
       :desc "Document selected" "c" #'copilot-chat-doc
       :desc "Fix selected" "f" #'copilot-chat-fix
       :desc "Optimize selected" "o" #'copilot-chat-optimize
       :desc "Write tests for selected" "t" #'copilot-chat-test
       :desc "Custom prompt with selection" "p" #'copilot-chat-custom-prompt-selection
       :desc "Current buffer to copilot chat" "s" #'copilot-chat-add-current-buffer
       :desc "Buffer list" "b" #'copilot-chat-list
       :desc "Previous prompt history" "h" #'copilot-chat-prompt-history-previous
       :desc "Next prompt history" "n" #'copilot-chat-prompt-history-next))
#+end_src

* YAS Snippets
#+begin_src elisp
(use-package! doom-snippets
  :load-path "~/Projects/snippets"
  :after yasnippet)
#+end_src

* Typescript
#+begin_src elisp
;; (setq-hook! 'javascript-mode-hook +format-with-lsp t)
;; (setq-hook! 'javascript-mode-hook +format-with 'prettier)
(setq-hook! 'javascript-mode-hook +format-with 'prettier)
(setq-hook! 'typescript-mode-hook +format-with 'prettier)
(setq-hook! 'typescript-tsx-mode-hook +format-with 'prettier)
;; (setq-hook! 'javascript-mode-hook +format-with 'eslint)
;; (setq-hook! 'typescript-mode-hook +format-with 'standard)
;; (setq-hook! 'javascript-mode-hook +format-with :none)
;; (setq typescript-indent-level 2)
;; Use standard-js
;; (setq-hook! 'js2-jsx-mode-hook +format-with 'standard)
;; (setq-hook! 'js-jsx-mode-hook +format-with 'standard)
;; (setq-hook! 'rjsx-mode-hook +format-with 'standard)
;; (setq-hook! 'js-mode-hook +format-with 'standard)
#+end_src

* Debug Emacs
#+begin_src elisp :tangle no
(setq debug-on-error t)
#+end_src
