#+title: Config

Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!

* TOC :toc:
- [[#setup][Setup]]
  - [[#lexical-binding][Lexical Binding]]
  - [[#my-custom-variables][My Custom Variables]]
  - [[#my-shared-modules][My Shared Modules]]
  - [[#conditional-machine-loading][Conditional Machine Loading]]
  - [[#my-custom-functions][My Custom Functions]]
- [[#editor][Editor]]
  - [[#beautify-logo][Beautify Logo]]
  - [[#personal-identification][Personal Identification]]
  - [[#font][Font]]
  - [[#theme][Theme]]
  - [[#line-numbers][Line Numbers]]
  - [[#emergency-log-messages-only][Emergency log messages only]]
  - [[#full-screen][Full Screen]]
  - [[#modeline][Modeline]]
- [[#projectile][Projectile]]
- [[#org][Org]]
  - [[#behavior][Behavior]]
  - [[#org-babel-config][Org Babel Config]]
  - [[#org-babel-tangle-specific-config-files][Org Babel Tangle Specific Config Files]]
- [[#dired][Dired]]
  - [[#configure-default-directory][Configure Default Directory]]
- [[#programming][Programming]]
  - [[#typescript][Typescript]]
  - [[#python][Python]]
  - [[#yaml][YAML]]
- [[#packages][Packages]]
  - [[#drag-lines][Drag Lines]]
  - [[#verb][Verb]]
  - [[#denote][Denote]]
  - [[#copilot][Copilot]]
  - [[#yas-snippets][YAS Snippets]]
- [[#debug-emacs][Debug Emacs]]

* Setup
** Lexical Binding
#+begin_src elisp
;; -*- lexical-binding: t; -*-
#+end_src

** My Custom Variables
#+begin_src elisp
(defvar my/org-babel-tangle-files '("zshrc.org")
  "List of Org files that should be auto-tangled on save.")
#+end_src

** My Shared Modules
#+begin_src elisp
(add-to-list 'load-path "~/.config/doom/modules")
#+end_src

** Conditional Machine Loading
Load any custom private configurations only to be loaded based on the host machine.
#+begin_src elisp
(cond
 ((member system-name '("S427544"))
  (add-load-path! "~/.config/work")
  (if (locate-library "my-work")
      (require 'my-work)
    (message "Warning: my-work.el not found.")))
 ((member system-name '("Pauls-MacBook-Air.local"))
  (add-load-path! "~/.config/home")
  (if (locate-library "my-mac")
      (require 'my-mac)
    (message "Warning: my-mac.el not found."))))
#+end_src

** My Custom Functions
*** Tangle all files in a specified directory
#+begin_src elisp
(defun my/tangle-org-files-in-directory (directory)
  "Tangle all .org files in the specified DIRECTORY."
  (interactive "DDirectory: ")
  (let ((org-files (directory-files-recursively directory "\\.org\\'")))
    (dolist (file org-files)
      (message "Tangling %s..." file)
      (org-babel-tangle-file file))))
#+end_src

*** Check formatter being used
#+begin_src elisp
(defun my/check-formatter-for-mode (mode)
  "Check the formatter used for a specific MODE."
  (interactive
   (list (intern (completing-read "Mode: " obarray
                                  (lambda (m)
                                    (and (fboundp m)
                                         (string-suffix-p "-mode" (symbol-name m))))
                                  t))))
  (with-temp-buffer
    (funcall mode)
    (message "Formatter for %s: %s" mode +format-with)))
#+end_src

* Editor
** Beautify Logo
#+begin_src elisp
(setq fancy-splash-image (concat doom-private-dir "teenjus-dance.jpeg"))
#+end_src

** Personal Identification
Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets. It is optional.
#+begin_src elisp :tangle no
(setq user-full-name "Paul Meier"
        user-mail-address "paulmartinmeier@gmail.com")
#+end_src

** Font
Doom exposes five (optional) variables for controlling fonts in Doom:

- `doom-font' -- the primary font to use
- `doom-variable-pitch-font' -- a non-monospace font (where applicable)
- `doom-big-font' -- used for `doom-big-font-mode'; use this for
    presentations or streaming.
- `doom-symbol-font' -- for symbols
- `doom-serif-font' -- for the `fixed-pitch-serif' face

See 'C-h v doom-font' for documentation and more examples of what they
accept. For example:

~Note~ I'm normally setting this in the machine specific settings.
#+begin_src elisp :tangle no
(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
    doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
#+end_src

If you or Emacs can't find your font, use 'M-x describe-font' to look them
up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
refresh your font settings. If Emacs still can't find your font, it likely
wasn't installed correctly. Font issues are rarely Doom issues!

** Theme
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:
#+begin_src elisp
(setq doom-theme 'doom-one)
#+end_src

** Line Numbers
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src elisp
(setq display-line-numbers-type t)
#+end_src

** Emergency log messages only
#+begin_src elisp
(setq warning-minimum-level :emergency)
#+end_src

** Full Screen
#+begin_src elisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

** Modeline
#+begin_src elisp
(display-battery-mode 1)
#+end_src

* Projectile
~Note:~ I'm setting this in host specific configurations.
#+begin_src elisp :tangle no
(setq projectile-project-search-path '("~/Projects"))
#+end_src

* Org
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!
#+begin_src elisp :tangle no
(setq org-directory "~/Org/")
#+end_src

** Behavior
#+begin_src elisp
(defun my/org-mode-setup ()
  (org-indent-mode)
  (variable-pitch-mode 1)
  (auto-fill-mode 0)
  (valign-mode 1)
  (visual-line-mode 1)
  (visual-fill-column-mode 1)
  (display-line-numbers-mode 0)
  (org-display-inline-images)
  (setq org-download-image-dir "./.attach")
  (setq evil-auto-indent nil)
  (setq org-attach-id-dir "./.attach")
  (setq org-image-actual-width nil)
  (setq visual-fill-column-center-text t)
  (setq org-log-into-drawer "LOGBOOK")
  (setq org-use-property-inheritance t))

(use-package! org
  :hook (org-mode . my/org-mode-setup)
  :config (define-key org-mode-map (kbd "C-c C-r") verb-command-map))
#+end_src

** Org Babel Config
#+begin_src elisp :tangle no
(setq org-babel-load-languages
      '((emacs-lisp . t)
        (python . t)
        (shell . t)
        (js . t)
        (mermaid . t)
        (scheme . t)
        (verb . t)
        (ein . t)
        (typescript . t)))
#+end_src

** Org Babel Tangle Specific Config Files
#+begin_src elisp
(defun my/org-babel-tangle-on-save ()
  "Auto-tangle specific Org files on save."
  (when (and (string= (file-name-extension buffer-file-name) "org")
             (member (file-name-nondirectory buffer-file-name)
                     my/org-babel-tangle-files))
    (org-babel-tangle)))

(add-hook 'after-save-hook 'my/org-babel-tangle-on-save)
#+end_src

* Dired
** Configure Default Directory
If non-nil, Dired tries to guess a default target directory.
#+begin_src elisp
(setq dired-dwim-target t)
#+end_src

* Programming
** Typescript
#+begin_src elisp
;; (setq-hook! 'javascript-mode-hook +format-with-lsp t)
;; (setq-hook! 'javascript-mode-hook +format-with 'prettier)
(setq-hook! 'javascript-mode-hook +format-with 'prettier)
(setq-hook! 'typescript-mode-hook +format-with 'prettier)
(setq-hook! 'typescript-tsx-mode-hook +format-with 'prettier)
;; (setq-hook! 'javascript-mode-hook +format-with 'eslint)
;; (setq-hook! 'typescript-mode-hook +format-with 'standard)
;; (setq-hook! 'javascript-mode-hook +format-with :none)
;; (setq typescript-indent-level 2)
;; Use standard-js
;; (setq-hook! 'js2-jsx-mode-hook +format-with 'standard)
;; (setq-hook! 'js-jsx-mode-hook +format-with 'standard)
;; (setq-hook! 'rjsx-mode-hook +format-with 'standard)
;; (setq-hook! 'js-mode-hook +format-with 'standard)
#+end_src

** Python
*** Jupyter
#+begin_src elisp :tangle no
(setq jupyter-python-command "/opt/homebrew/bin/python3")
#+end_src

** YAML
*** Disable format on save for yaml files
#+begin_src elisp
(defun my/disable-format-on-save-for-yaml ()
  "Disable format on save for YAML files."
  (when (or (string-equal (file-name-extension buffer-file-name) "yml")
            (string-equal (file-name-extension buffer-file-name) "yaml"))
    (setq +format-with nil)))

(add-hook 'yaml-mode-hook #'my/disable-format-on-save-for-yaml)
#+end_src

* Packages
Whenever you reconfigure a package, make sure to wrap your config in an
`after!' block, otherwise Doom's defaults may override your settings. E.g.

    (after! PACKAGE
    (setq x y))

The exceptions to this rule:

    - Setting file/directory variables (like `org-directory')
    - Setting variables which explicitly tell you to set them before their
    package is loaded (see 'C-h v VARIABLE' to look up their documentation).
    - Setting doom variables (which start with 'doom-' or '+').

Here are some additional functions/macros that will help you configure Doom.

- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
    this file. Emacs searches the `load-path' when you load packages with
    `require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.
Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
etc).

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.

** Drag Lines
#+begin_src elisp
(use-package! drag-stuff
   :defer t
   :init
  (map! "<M-up>"    #'drag-stuff-up
        "<M-down>"  #'drag-stuff-down
        "<M-left>"  #'drag-stuff-left
        "<M-right>" #'drag-stuff-right))
#+end_src

** Verb
#+begin_src elisp
(map! :leader
      (:prefix ("v" . "verb")
       :desc "send request"
       "r" #'verb-send-request-on-point-other-window))
(setq verb-suppress-load-unsecure-prelude-warning t)
#+end_src

** Denote
*** Configure
#+begin_src elisp
(use-package! denote
  :init
  ;; (require 'denote-journal-extras)
  (add-hook 'denote-after-new-note-hook #'project-and-active-to-agenda)
  (add-hook 'denote-journal-extras-hook 'my-denote-tmr)
  :custom
  (denote-known-keywords '("journal" "active" "project"))
  (denote-sort-keywords t)
  (denote-prompts '(subdirectory title keywords templates)))
  :config
  (setq denote-dired-directories
      (list (or (getenv "DENOTE_DIRED_DIRECTORIES") "~/Notes")))
  (setq denote-directory (or (getenv "DENOTE_DIRECTORY") "~/Notes"))
  (setq denote-journal-extras-directory (or (getenv "DENOTE_JOURNAL_EXTRAS_DIRECTORY") "~/Notes"))
#+end_src

*** Customize Denote
#+begin_src elisp
(unless (boundp 'denote-templates)
    (setq denote-templates '()))
;; (setq denote-file-type "markdown-yaml")
(push '(journal . "\n\n* Daily Journal\n\n") denote-templates)
#+end_src

*** Keybindings
#+begin_src elisp
(map! :leader
      (:prefix ("e" . "denote")
       :desc "New Note" "n" #'denote
       :desc "Insert Link" "i" #'denote-insert-link
       :desc "New Journal" "j" #'denote-journal-extras-new-or-existing-entry
       :desc "Find in Notes" "f" #'consult-notes-search-in-all-notes
       :desc "Search with Xeft" "x" #'xeft
       :desc "Search Notes" "s" #'consult-notes))
#+end_src

*** Consult Notes
#+begin_src elisp
(use-package! consult-notes
  :config
  (setq consult-notes-file-dir-sources
      (list (list "Notes" ?o (or (getenv "CONSULT_NOTES_FILE_DIR_SOURCES") "~/Notes"))))
  (when (locate-library "denote")
    (consult-notes-denote-mode)))
  ;; search only for text files in denote dir
  ;; (setq consult-notes-denote-files-function (function denote-directory-text-only-files)))
#+end_src

*** Xeft
#+begin_src elisp
(use-package! xeft
    :after denote
    :config
    (setq xeft-directory (or (getenv "DENOTE_DIRECTORY") "~/Notes"))
    (setq xeft-recursive t))
#+end_src

** Copilot
*** Copilot Keybindings
#+begin_src elisp
(map! :leader
      (:prefix ("l" . "co-chat")
       :desc "Chat Prompt" "p" #'copilot-chat-prompt
       :desc "Reset" "r" #'copilot-chat-reset
       :desc "Chat buffers" "d" #'copilot-chat-display
       :desc "Explain selected" "e" #'copilot-chat-explain
       :desc "Review selected" "v" #'copilot-chat-review
       :desc "Document selected" "c" #'copilot-chat-doc
       :desc "Fix selected" "f" #'copilot-chat-fix
       :desc "Optimize selected" "o" #'copilot-chat-optimize
       :desc "Write tests for selected" "t" #'copilot-chat-test
       :desc "Custom prompt with selection" "p" #'copilot-chat-custom-prompt-selection
       :desc "Current buffer to copilot chat" "s" #'copilot-chat-add-current-buffer
       :desc "Buffer list" "b" #'copilot-chat-list
       :desc "Previous prompt history" "h" #'copilot-chat-prompt-history-previous
       :desc "Next prompt history" "n" #'copilot-chat-prompt-history-next))
#+end_src

** YAS Snippets
#+begin_src elisp
(use-package! doom-snippets
  :load-path "~/Projects/snippets"
  :after yasnippet)
#+end_src

* Debug Emacs
#+begin_src elisp :tangle no
(setq debug-on-error t)
#+end_src
