* Headers
#+begin_src elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

* Low Level
** Custom message handler
This message handler will add the ~@@@~ prefix to any messages I provide.
#+begin_src elisp
(defun my-message (format-string &rest args)
  "Display a personal message prefixed with @@@ in *Messages* buffer."
  (apply #'message (concat "@@@ " format-string) args))
#+end_src

* Custom Functions
** Add folder to load path
#+begin_src elisp
(defun my/add-to-load-path (&rest paths)
    "Add each PATH in PATHS to `load-path` and log them using `my-message`."
  (dolist (path paths)
    (add-to-list 'load-path path)
    (my-message "Added %s to load-path" path)))
#+end_src

** Host machine location
This function sets a variable that can be used for a conditional on home/work separation.
#+begin_src elisp
(setq my-location
      (cond
       ((member system-name '("S427544")) "work")
       ((member system-name '("MacBook-Pro.local")) "home")
       (t "unknown")))
(my-message "Current location: %s" my-location)
#+end_src

** Tangle all files in a specified directory
#+begin_src elisp
(defun my/tangle-org-files-in-directory (directory)
  "Tangle all .org files in the specified DIRECTORY."
  (interactive "DDirectory: ")
  (let ((org-files (directory-files-recursively directory "\\.org\\'")))
    (dolist (file org-files)
      (my-message "Tangling %s..." file)
      (org-babel-tangle-file file))))
#+end_src

** Org Babel Tangle Specific Config Files
#+begin_src elisp
(defun my/org-babel-tangle-on-save ()
  "Auto-tangle specific Org files on save."
  (when (and (string= (file-name-extension buffer-file-name) "org")
             (member (file-name-nondirectory buffer-file-name)
                     my/org-babel-tangle-files))
    (org-babel-tangle)))

(add-hook 'after-save-hook 'my/org-babel-tangle-on-save)
#+end_src

** Check formatter being used
#+begin_src elisp
(defun my/check-formatter-for-mode (mode)
  "Check the formatter used for a specific MODE."
  (interactive
   (list (intern (completing-read "Mode: " obarray
                                  (lambda (m)
                                    (and (fboundp m)
                                         (string-suffix-p "-mode" (symbol-name m))))
                                  t))))
  (with-temp-buffer
    (funcall mode)
    (message "Formatter for %s: %s" mode +format-with)))
#+end_src

** Get Org title
#+begin_src elisp
(defun my/org-title-slug ()
  "Return a filesystem-safe slug based on #+title or buffer name."
  (let* ((title (or (org-get-title)
                    (file-name-base (or (buffer-file-name) "diagram"))))
         (slug  (downcase
                 (replace-regexp-in-string "[^[:alnum:]]+" "-" title))))
    slug))
#+end_src

* My Variables
** Auto org babel tangle files
List of Org files that should be auto-tangled on save.
#+begin_src elisp
(setq my/org-babel-tangle-files '("zshrc.org" "my-home.org" "my-work.org" "work-config.org" "~/.config/my-work-python.org" "~/dotfiles/zshrc-work.org"))
#+end_src


* Shared Modules
#+begin_src elisp
(my/add-to-load-path "~/.config/doom/modules")
(require 'isbn-to-bibtex)
(require 'my-book-cover)
(require 'lit-mode)
(require 'comfy-mode)
#+end_src

* Conditional Machine Loading
This is for private code or anything that shouldn't be included in a public repo.
#+begin_src elisp
(let ((config-dir (format "~/.config/%s" my-location))
      (config-lib (format "my-%s" my-location)))
  (add-to-list 'load-path config-dir)
  (my-message "Added %s to load-path" config-dir)
  (if (locate-library config-lib)
      (require (intern config-lib))
    (my-message "Warning: %s.el not found." config-lib)))
#+end_src

* Beautify Logo
#+begin_src elisp
(setq fancy-splash-image (concat doom-private-dir "alfie.png"))
#+end_src

* Editor
** Drag Lines
#+begin_src elisp
(use-package! drag-stuff
   :defer t
   :init
  (map! "<M-up>" #'drag-stuff-up
        "<M-down>" #'drag-stuff-down
        "<M-left>" #'drag-stuff-left
        "<M-right>" #'drag-stuff-right))
#+end_src

** Emergency log messages only
#+begin_src elisp
(setq warning-minimum-level :emergency)
;;(setq compilation-scroll-output t)
#+end_src

** Full Screen
Both options commented out are not working correctly on MAC
#+begin_src elisp
;; (add-to-list 'default-frame-alist '(fullscreen . maximized))
(add-hook 'window-setup-hook #'toggle-frame-maximized)
;;(add-hook 'window-setup-hook #'toggle-frame-fullscreen)
#+end_src

** Fonts
To fix unicode boxes displaying for org mode bullets on a ~Macbook~ install this font.
#+begin_src bash :tangle no
brew install font-noto-sans-symbols-2
#+end_src

#+begin_src elisp
;; "SN Pro" "Roboto Mono" "Fira Code" "Noto Sans Symbols 2"
(setq doom-font (font-spec :family "Fira Code" :size 15)
      doom-variable-pitch-font (font-spec :family "SN Pro" :size 15 :weight 'medium)
      doom-big-font (font-spec :family "Fira Code" :size 24))
#+end_src

** Modeline
#+begin_src elisp
(display-battery-mode 1)
#+end_src

* Projectile
#+begin_src elisp
(setq projectile-project-search-path '("~/Projects"))
#+end_src

* Dired
** Configure Default Directory
If non-nil, Dired tries to guess a default target directory.
#+begin_src elisp
(setq dired-dwim-target t)
#+end_src

* Encryption
#+begin_src elisp
(after! epg
  (setq epg-gpg-program "/usr/local/bin/gpg"
        epg-pinentry-mode 'ask))

(epa-file-enable)
#+end_src

* Work Configuration (Conditional)
Loads work-specific sensitive configuration only on the work machine.
The work config lives in =work-config.org= which is gitignored.
#+begin_src elisp
(when (string= my-location "work")
  (let ((work-config (expand-file-name "work-config.el" doom-private-dir)))
    (if (file-exists-p work-config)
        (progn
          (load work-config)
          (my-message "Loaded work configuration from %s" work-config))
      (my-message "Warning: work-config.el not found. Tangle work-config.org to generate it."))))
#+end_src

* Jinja2 Support
** YAML with Jinja2 Syntax
#+begin_src elisp
(add-to-list 'auto-mode-alist '("\\.yml\\'" . yaml-mode))
(add-to-list 'auto-mode-alist '("\\.yaml\\'" . yaml-mode))
(add-to-list 'auto-mode-alist '("\\.j2.yml\\'" . jinja2-mode))
(add-to-list 'auto-mode-alist '("\\.j2.yaml\\'" . jinja2-mode))

(add-hook 'jinja2-mode-hook
          (lambda ()
            (setq jinja2-enable-indent t)))
#+end_src

* Copilot
** Copilot Configuration
Accept completion from copilot and fallback to company.
#+begin_src elisp
(use-package! copilot
  :hook (prog-mode . copilot-mode)
  :bind (:map copilot-completion-map
              ("<tab>" . 'copilot-accept-completion)
              ("TAB" . 'copilot-accept-completion)
              ("C-TAB" . 'copilot-accept-completion-by-word)
              ("C-<tab>" . 'copilot-accept-completion-by-word)))

(use-package! gh-copilot-chat
  :defer t
  :config
  (map! :leader
        (:prefix ("o" . "open")
         (:prefix ("c" . "copilot")
          :desc "Chat" "c" #'gh-copilot-chat-display
          :desc "Transient Menu" "t" #'gh-copilot-chat-transient
          :desc "Add Buffer" "a" #'gh-copilot-chat-add-current-buffer
          :desc "Remove Buffer" "r" #'gh-copilot-chat-del-current-buffer
          :desc "Buffer List" "b" #'gh-copilot-chat-list
          :desc "Reset" "R" #'gh-copilot-chat-reset
          :desc "Explain" "e" #'gh-copilot-chat-explain
          :desc "Review" "v" #'gh-copilot-chat-review
          :desc "Docs" "d" #'gh-copilot-chat-doc
          :desc "Fix" "f" #'gh-copilot-chat-fix
          :desc "Optimize" "o" #'gh-copilot-chat-optimize
          :desc "Tests" "T" #'gh-copilot-chat-test
          :desc "Custom Prompt" "p" #'gh-copilot-chat-custom-prompt-function
          :desc "Previous Message" "p" #'gh-copilot-chat-previous-message
          :desc "Next Message" "n" #'gh-copilot-chat-next-message
          :desc "Copy Last Response" "y" #'gh-copilot-chat-copy-last-response
          :desc "Send Region" "s" #'gh-copilot-chat-send-region
          :desc "Open Chat Popup" "w" #'gh-copilot-chat-popup))))
#+end_src

* Org
** Org Setup
#+begin_src elisp
(setq org-directory (or (getenv "ORG_DIRECTORY") "~/Org")
      org-agenda-files (list (or (getenv "ORG_AGENDA_FILES") "~/Org")))

(defun my/org-mode-setup ()
  (org-display-inline-images)
  (setq evil-auto-indent nil)
  (setq org-attach-id-dir ".attach")
  (setq org-attach-use-inheritance t)
  (setq org-attach-store-link-p t)
  (setq org-attach-dir-relative t)
  (setq org-image-actual-width nil)
  (setq org-log-into-drawer "LOGBOOK")
  (setq org-use-property-inheritance t)
  (setq org-pandoc-options-for-latex-pdf '((pdf-engine . "xelatex"))))

(after! org
  (add-hook 'org-mode-hook #'my/org-mode-setup)

  (org-babel-do-load-languages
    'org-babel-load-languages
    (append org-babel-load-languages
      '((emacs-lisp . t)
        (python . t)
        (shell . t)
        (js . t)
        (mermaid . t)
        (scheme . t)
        (verb . t)
        (ein . t)
        (typescript . t)))))
#+end_src

** Org Create TODOs from block of lines
#+begin_src elisp
(defun org-set-line-checkbox (arg)
  (interactive "P")
  (let ((n (or arg 1)))
    (when (region-active-p)
      (setq n (count-lines (region-beginning)
                           (region-end)))
      (goto-char (region-beginning)))
    (dotimes (i n)
      (beginning-of-line)
      (insert "- [ ] ")
      (forward-line))
    (beginning-of-line)))
#+end_src

** Org Timeblock
#+begin_src elisp
(use-package! org-timeblock
  :config
  (setq org-timeblock-inbox-file "timeblock.org"))
#+end_src

* Verb
#+begin_src elisp
(use-package! verb
  :defer t
  :config
  (setq verb-suppress-load-unsecure-prelude-warning t)

  (after! org
    (define-key org-mode-map (kbd "C-c C-r") verb-command-map)))

(map! :leader
      (:prefix ("v" . "verb")
       :desc "send request"
       "r" #'verb-send-request-on-point-other-window))
#+end_src

* Denote
** Configuration
#+begin_src elisp
(use-package! denote
  :custom
  (denote-directory "~/Notes")
  (denote-prompts '(subdirectory title keywords template))
  (denote-templates '((generic . "")))
  (denote-known-keywords '("nm" "technology" "reference" "guide" "project" "moc" "found" "caas" "education" "personal"))
  (denote-date-prompt-use-org-read-date t))
#+end_src

** Keybindings
#+begin_src elisp
(map! :leader
      (:prefix ("e" . "notes")
       :desc "New Note"        "n" #'denote
       :desc "Insert Link"     "i" #'denote-link
       :desc "Journal Entry"   "j" #'denote-journal-extras-new-or-existing-entry
       :desc "Find Note"       "f" #'consult-notes
       :desc "Search Notes"    "s" #'consult-notes-search-in-all-notes
       :desc "Follow Link"     "l" #'denote-link-or-create
       :desc "Backlinks"       "b" #'denote-backlinks
       :desc "Find by Tag"     "t" #'denote-keywords-find))
#+end_src

** Expand Org Source Block
#+begin_src elisp
(map! :leader
      :desc "Expand Org source block"
      "y b" #'org-babel-expand-src-block)
#+end_src

** Consult Notes
#+begin_src elisp
(use-package! consult-notes
  :config
  (consult-notes-denote-mode))
#+end_src

* YAS Snippets
#+begin_src elisp
(use-package! doom-snippets
  :load-path "~/Projects/snippets"
  :after yasnippet)
#+end_src

* Typescript
#+begin_src elisp
;; (setq-hook! 'javascript-mode-hook +format-with-lsp t)
;; (setq-hook! 'javascript-mode-hook +format-with 'prettier)
(setq-hook! 'javascript-mode-hook +format-with 'prettier)
(setq-hook! 'typescript-mode-hook +format-with 'prettier)
(setq-hook! 'typescript-tsx-mode-hook +format-with 'prettier)
;; (setq-hook! 'javascript-mode-hook +format-with 'eslint)
;; (setq-hook! 'typescript-mode-hook +format-with 'standard)
;; (setq-hook! 'javascript-mode-hook +format-with :none)
;; (setq typescript-indent-level 2)
;; Use standard-js
;; (setq-hook! 'js2-jsx-mode-hook +format-with 'standard)
;; (setq-hook! 'js-jsx-mode-hook +format-with 'standard)
;; (setq-hook! 'rjsx-mode-hook +format-with 'standard)
;; (setq-hook! 'js-mode-hook +format-with 'standard)
#+end_src

* Debug Emacs
#+begin_src elisp :tangle no
(setq debug-on-error t)
#+end_src
